### ISSUE TITLE
HomePage: Apply required visual style

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/peo-scholarships#82]
![Screen Shot 2021-02-10 at 10 19 01 AM](https://user-images.githubusercontent.com/5502/107553262-6ab6f980-6b89-11eb-9141-d01875620881.png)

**Comment by ybakos** [comment]
Also see https://www.peointernational.org/

**Comment by ybakos** [comment]
Via A. Fleck  2/11/2021.

To answer your questions…

The international website has a great deal of functionality that we really don’t need, so I  would not want your time into that.  Here is a link to the oregon website.  I think the look can be very simple and easy with the link to apply.  https://peooregon.org/

I would say the colors are not important but the logo is and I will get the right one to you.

For transcripts, if the applicant graduated from high school within the last 10 years we ask for those but if it has been longer than 10 years, we do not request them.  We do ask for transcripts from any post-high school education.

We really haven’t changed the scholarship very much from year to year.  If it does change it is mainly the essay questions but I would say we have not figured out the financial piece yet and that may need to be changed at some point in the future.

Does that help?

**Comment by ybakos** [comment]
![P E O  Primary Logo PNG - RGB Color - 2x2](https://user-images.githubusercontent.com/5502/107823464-b1952280-6d34-11eb-87e5-c72c76e120e9.png)
![logo](https://user-images.githubusercontent.com/5502/107823470-b4901300-6d34-11eb-942b-8b7c6c164c78.png)

**Comment by Amber-K** [comment]
I need to make it so the signed out successfully notification at the top of the screen goes over the title bar image instead of offsetting it.
